name: mediarescueadmin
description: "MediaRescue Admin - Serverless administration dashboard."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_riverpod: ^2.5.0
  flutter_svg: ^2.0.0
  liquid_glass_easy: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/service_account.json
    - assets/bg_image.jpg
